version: '3'

services:
  #MySQL
  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: locker
      MYSQL_USER: ahmad
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password 
 # PHP with PDO
  web:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_web
    depends_on:
      - database
    volumes:
      - .:/var/www/html/:delegated
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
