apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: appsvc
  name: appsvc
spec:
  type: NodePort
  selector:
    app: appdeployemnt
  ports:
  - name: targetport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007

