apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dbdeployemnt
  name: dbdeployemnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbdeployemnt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dbdeployemnt
    spec:
      containers:
      - image: mysql:5.7
        name: database
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sqlinit
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: sqlinit
              key: MYSQL_USER

        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath:  /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
