apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dbsvc
  name: dbsvc
spec:
  # type: NodePort
  selector:
    app: dbdeployemnt
  ports:
  - port: 3306
  clusterIP: None
  # - name: targetport
  #   protocol: TCP
  #   targetPort: 3306
  #   nodePort: 30006

