apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dbsvc
  name: dbsvc
spec:
  type: NodePort
  selector:
    app: dbdeployemnt
  ports:
  - name: targetport
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30006

