apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        imagePullPolicy: IfNotPresent

        env:
            - name: PMA_HOST
              value: "dbsvc"

            - name: PMA_PORT
              value: "3306"

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-root-password #the password on mysql-secret.yaml and is base64 decoded
        ports:
        - name: phpmyadmin
          containerPort: 80