apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - name: phpmyadmin
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001